// Copyright Contributors to Agones a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ActivePeriodApplyConfiguration represents a declarative configuration of the ActivePeriod type for use
// with apply.
//
// ActivePeriod defines the time period that the policy is applied.
type ActivePeriodApplyConfiguration struct {
	// Timezone to be used for the startCron field. If not set, startCron is defaulted to the UTC timezone.
	Timezone *string `json:"timezone,omitempty"`
	// StartCron defines when the policy should be applied.
	// If not set, the policy is always to be applied within the start and end time.
	// This field must conform to UNIX cron syntax.
	StartCron *string `json:"startCron,omitempty"`
	// Duration is the length of time that the policy is applied.
	// If not set, the duration is indefinite.
	// A duration string is a possibly signed sequence of decimal numbers,
	// (e.g. "300ms", "-1.5h" or "2h45m").
	// The representation limits the largest representable duration to approximately 290 years.
	// Valid time units are "ns", "us" (or "µs"), "ms", "s", "m", "h".
	Duration *string `json:"duration,omitempty"`
}

// ActivePeriodApplyConfiguration constructs a declarative configuration of the ActivePeriod type for use with
// apply.
func ActivePeriod() *ActivePeriodApplyConfiguration {
	return &ActivePeriodApplyConfiguration{}
}

// WithTimezone sets the Timezone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timezone field is set to the value of the last call.
func (b *ActivePeriodApplyConfiguration) WithTimezone(value string) *ActivePeriodApplyConfiguration {
	b.Timezone = &value
	return b
}

// WithStartCron sets the StartCron field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartCron field is set to the value of the last call.
func (b *ActivePeriodApplyConfiguration) WithStartCron(value string) *ActivePeriodApplyConfiguration {
	b.StartCron = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *ActivePeriodApplyConfiguration) WithDuration(value string) *ActivePeriodApplyConfiguration {
	b.Duration = &value
	return b
}
