// Copyright Contributors to Agones a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// BetweenApplyConfiguration represents a declarative configuration of the Between type for use
// with apply.
//
// Between defines the time period that the policy is eligible to be applied.
type BetweenApplyConfiguration struct {
	// Start is the datetime that the policy is eligible to be applied.
	// This field must conform to RFC3339 format. If this field not set or is in the past, the policy is eligible to be applied
	// as soon as the fleet autoscaler is running.
	Start *metav1.Time `json:"start,omitempty"`
	// End is the datetime that the policy is no longer eligible to be applied.
	// This field must conform to RFC3339 format. If not set, the policy is always eligible to be applied, after the start time above.
	End *metav1.Time `json:"end,omitempty"`
}

// BetweenApplyConfiguration constructs a declarative configuration of the Between type for use with
// apply.
func Between() *BetweenApplyConfiguration {
	return &BetweenApplyConfiguration{}
}

// WithStart sets the Start field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Start field is set to the value of the last call.
func (b *BetweenApplyConfiguration) WithStart(value metav1.Time) *BetweenApplyConfiguration {
	b.Start = &value
	return b
}

// WithEnd sets the End field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the End field is set to the value of the last call.
func (b *BetweenApplyConfiguration) WithEnd(value metav1.Time) *BetweenApplyConfiguration {
	b.End = &value
	return b
}
