// Copyright Contributors to Agones a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// BufferPolicyApplyConfiguration represents a declarative configuration of the BufferPolicy type for use
// with apply.
//
// BufferPolicy controls the desired behavior of the buffer policy.
type BufferPolicyApplyConfiguration struct {
	// MaxReplicas is the maximum amount of replicas that the fleet may have.
	// It must be bigger than both MinReplicas and BufferSize
	MaxReplicas *int32 `json:"maxReplicas,omitempty"`
	// MinReplicas is the minimum amount of replicas that the fleet must have
	// If zero, it is ignored.
	// If non zero, it must be smaller than MaxReplicas and bigger than BufferSize
	MinReplicas *int32 `json:"minReplicas,omitempty"`
	// BufferSize defines how many replicas the autoscaler tries to have ready all the time
	// Value can be an absolute number (ex: 5) or a percentage of desired gs instances (ex: 15%)
	// Absolute number is calculated from percentage by rounding up.
	// Example: when this is set to 20%, the autoscaler will make sure that 20%
	// of the fleet's game server replicas are ready. When this is set to 20,
	// the autoscaler will make sure that there are 20 available game servers
	// Must be bigger than 0
	// Note: by "ready" we understand in this case "non-allocated"; this is done to ensure robustness
	// and computation stability in different edge case (fleet just created, not enough
	// capacity in the cluster etc)
	BufferSize *intstr.IntOrString `json:"bufferSize,omitempty"`
}

// BufferPolicyApplyConfiguration constructs a declarative configuration of the BufferPolicy type for use with
// apply.
func BufferPolicy() *BufferPolicyApplyConfiguration {
	return &BufferPolicyApplyConfiguration{}
}

// WithMaxReplicas sets the MaxReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxReplicas field is set to the value of the last call.
func (b *BufferPolicyApplyConfiguration) WithMaxReplicas(value int32) *BufferPolicyApplyConfiguration {
	b.MaxReplicas = &value
	return b
}

// WithMinReplicas sets the MinReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinReplicas field is set to the value of the last call.
func (b *BufferPolicyApplyConfiguration) WithMinReplicas(value int32) *BufferPolicyApplyConfiguration {
	b.MinReplicas = &value
	return b
}

// WithBufferSize sets the BufferSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BufferSize field is set to the value of the last call.
func (b *BufferPolicyApplyConfiguration) WithBufferSize(value intstr.IntOrString) *BufferPolicyApplyConfiguration {
	b.BufferSize = &value
	return b
}
