// Copyright Contributors to Agones a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// CounterPolicyApplyConfiguration represents a declarative configuration of the CounterPolicy type for use
// with apply.
//
// CounterPolicy controls the desired behavior of the Counter autoscaler policy.
type CounterPolicyApplyConfiguration struct {
	// Key is the name of the Counter. Required field.
	Key *string `json:"key,omitempty"`
	// MaxCapacity is the maximum aggregate Counter total capacity across the fleet.
	// MaxCapacity must be bigger than both MinCapacity and BufferSize. Required field.
	MaxCapacity *int64 `json:"maxCapacity,omitempty"`
	// MinCapacity is the minimum aggregate Counter total capacity across the fleet.
	// If zero, MinCapacity is ignored.
	// If non zero, MinCapacity must be smaller than MaxCapacity and bigger than BufferSize.
	MinCapacity *int64 `json:"minCapacity,omitempty"`
	// BufferSize is the size of a buffer of counted items that are available in the Fleet (available
	// capacity). Value can be an absolute number (ex: 5) or a percentage of desired gs instances
	// (ex: 5%). An absolute number is calculated from percentage by rounding up.
	// Must be bigger than 0. Required field.
	BufferSize *intstr.IntOrString `json:"bufferSize,omitempty"`
}

// CounterPolicyApplyConfiguration constructs a declarative configuration of the CounterPolicy type for use with
// apply.
func CounterPolicy() *CounterPolicyApplyConfiguration {
	return &CounterPolicyApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *CounterPolicyApplyConfiguration) WithKey(value string) *CounterPolicyApplyConfiguration {
	b.Key = &value
	return b
}

// WithMaxCapacity sets the MaxCapacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxCapacity field is set to the value of the last call.
func (b *CounterPolicyApplyConfiguration) WithMaxCapacity(value int64) *CounterPolicyApplyConfiguration {
	b.MaxCapacity = &value
	return b
}

// WithMinCapacity sets the MinCapacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinCapacity field is set to the value of the last call.
func (b *CounterPolicyApplyConfiguration) WithMinCapacity(value int64) *CounterPolicyApplyConfiguration {
	b.MinCapacity = &value
	return b
}

// WithBufferSize sets the BufferSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BufferSize field is set to the value of the last call.
func (b *CounterPolicyApplyConfiguration) WithBufferSize(value intstr.IntOrString) *CounterPolicyApplyConfiguration {
	b.BufferSize = &value
	return b
}
