// Copyright Contributors to Agones a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// FleetAutoscalerSpecApplyConfiguration represents a declarative configuration of the FleetAutoscalerSpec type for use
// with apply.
//
// FleetAutoscalerSpec is the spec for a Fleet Scaler
type FleetAutoscalerSpecApplyConfiguration struct {
	FleetName *string `json:"fleetName,omitempty"`
	// Autoscaling policy
	Policy *FleetAutoscalerPolicyApplyConfiguration `json:"policy,omitempty"`
	// Sync defines when FleetAutoscalers runs autoscaling
	Sync *FleetAutoscalerSyncApplyConfiguration `json:"sync,omitempty"`
}

// FleetAutoscalerSpecApplyConfiguration constructs a declarative configuration of the FleetAutoscalerSpec type for use with
// apply.
func FleetAutoscalerSpec() *FleetAutoscalerSpecApplyConfiguration {
	return &FleetAutoscalerSpecApplyConfiguration{}
}

// WithFleetName sets the FleetName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FleetName field is set to the value of the last call.
func (b *FleetAutoscalerSpecApplyConfiguration) WithFleetName(value string) *FleetAutoscalerSpecApplyConfiguration {
	b.FleetName = &value
	return b
}

// WithPolicy sets the Policy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Policy field is set to the value of the last call.
func (b *FleetAutoscalerSpecApplyConfiguration) WithPolicy(value *FleetAutoscalerPolicyApplyConfiguration) *FleetAutoscalerSpecApplyConfiguration {
	b.Policy = value
	return b
}

// WithSync sets the Sync field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Sync field is set to the value of the last call.
func (b *FleetAutoscalerSpecApplyConfiguration) WithSync(value *FleetAutoscalerSyncApplyConfiguration) *FleetAutoscalerSpecApplyConfiguration {
	b.Sync = value
	return b
}
