// Copyright Contributors to Agones a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	intstr "k8s.io/apimachinery/pkg/util/intstr"
)

// ListPolicyApplyConfiguration represents a declarative configuration of the ListPolicy type for use
// with apply.
//
// ListPolicy controls the desired behavior of the List autoscaler policy.
type ListPolicyApplyConfiguration struct {
	// Key is the name of the List. Required field.
	Key *string `json:"key,omitempty"`
	// MaxCapacity is the maximum aggregate List total capacity across the fleet.
	// MaxCapacity must be bigger than both MinCapacity and BufferSize. Required field.
	MaxCapacity *int64 `json:"maxCapacity,omitempty"`
	// MinCapacity is the minimum aggregate List total capacity across the fleet.
	// If zero, it is ignored.
	// If non zero, it must be smaller than MaxCapacity and bigger than BufferSize.
	MinCapacity *int64 `json:"minCapacity,omitempty"`
	// BufferSize is the size of a buffer based on the List capacity that is available over the
	// current aggregate List length in the Fleet (available capacity). It can be specified either
	// as an absolute value (i.e. 5) or percentage format (i.e. 5%).
	// Must be bigger than 0. Required field.
	BufferSize *intstr.IntOrString `json:"bufferSize,omitempty"`
}

// ListPolicyApplyConfiguration constructs a declarative configuration of the ListPolicy type for use with
// apply.
func ListPolicy() *ListPolicyApplyConfiguration {
	return &ListPolicyApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ListPolicyApplyConfiguration) WithKey(value string) *ListPolicyApplyConfiguration {
	b.Key = &value
	return b
}

// WithMaxCapacity sets the MaxCapacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxCapacity field is set to the value of the last call.
func (b *ListPolicyApplyConfiguration) WithMaxCapacity(value int64) *ListPolicyApplyConfiguration {
	b.MaxCapacity = &value
	return b
}

// WithMinCapacity sets the MinCapacity field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinCapacity field is set to the value of the last call.
func (b *ListPolicyApplyConfiguration) WithMinCapacity(value int64) *ListPolicyApplyConfiguration {
	b.MinCapacity = &value
	return b
}

// WithBufferSize sets the BufferSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BufferSize field is set to the value of the last call.
func (b *ListPolicyApplyConfiguration) WithBufferSize(value intstr.IntOrString) *ListPolicyApplyConfiguration {
	b.BufferSize = &value
	return b
}
