// Copyright Contributors to Agones a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	agonesv1 "agones.dev/agones/pkg/apis/agones/v1"
)

// EvictionApplyConfiguration represents a declarative configuration of the Eviction type for use
// with apply.
//
// Eviction specifies the eviction tolerance of the GameServer
type EvictionApplyConfiguration struct {
	// Game server supports termination via SIGTERM:
	// - Always: Allow eviction for both Cluster Autoscaler and node drain for upgrades
	// - OnUpgrade: Allow eviction for upgrades alone
	// - Never (default): Pod should run to completion
	Safe *agonesv1.EvictionSafe `json:"safe,omitempty"`
}

// EvictionApplyConfiguration constructs a declarative configuration of the Eviction type for use with
// apply.
func Eviction() *EvictionApplyConfiguration {
	return &EvictionApplyConfiguration{}
}

// WithSafe sets the Safe field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Safe field is set to the value of the last call.
func (b *EvictionApplyConfiguration) WithSafe(value agonesv1.EvictionSafe) *EvictionApplyConfiguration {
	b.Safe = &value
	return b
}
