// Copyright Contributors to Agones a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	apis "agones.dev/agones/pkg/apis"
)

// GameServerSetSpecApplyConfiguration represents a declarative configuration of the GameServerSetSpec type for use
// with apply.
//
// GameServerSetSpec the specification for GameServerSet
type GameServerSetSpecApplyConfiguration struct {
	// Replicas are the number of GameServers that should be in this set
	Replicas *int32 `json:"replicas,omitempty"`
	// Labels and Annotations to apply to GameServers when the number of Allocated GameServers drops below
	// the desired replicas on the underlying `GameServerSet`
	AllocationOverflow *AllocationOverflowApplyConfiguration `json:"allocationOverflow,omitempty"`
	// Scheduling strategy. Defaults to "Packed".
	Scheduling *apis.SchedulingStrategy `json:"scheduling,omitempty"`
	// [Stage: Beta]
	// [FeatureFlag:CountsAndLists]
	// `Priorities` configuration alters scale down logic in Fleets based on the configured available capacity order under that key.
	//
	// Priority of sorting is in descending importance. I.e. The position 0 `priority` entry is checked first.
	//
	// For `Packed` strategy scale down, this priority list will be the tie-breaker within the node, to ensure optimal
	// infrastructure usage while also allowing some custom prioritisation of `GameServers`.
	//
	// For `Distributed` strategy scale down, the entire `Fleet` will be sorted by this priority list to provide the
	// order of `GameServers` to delete on scale down.
	Priorities []PriorityApplyConfiguration `json:"priorities,omitempty"`
	// Template the GameServer template to apply for this GameServerSet
	Template *GameServerTemplateSpecApplyConfiguration `json:"template,omitempty"`
}

// GameServerSetSpecApplyConfiguration constructs a declarative configuration of the GameServerSetSpec type for use with
// apply.
func GameServerSetSpec() *GameServerSetSpecApplyConfiguration {
	return &GameServerSetSpecApplyConfiguration{}
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *GameServerSetSpecApplyConfiguration) WithReplicas(value int32) *GameServerSetSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithAllocationOverflow sets the AllocationOverflow field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AllocationOverflow field is set to the value of the last call.
func (b *GameServerSetSpecApplyConfiguration) WithAllocationOverflow(value *AllocationOverflowApplyConfiguration) *GameServerSetSpecApplyConfiguration {
	b.AllocationOverflow = value
	return b
}

// WithScheduling sets the Scheduling field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Scheduling field is set to the value of the last call.
func (b *GameServerSetSpecApplyConfiguration) WithScheduling(value apis.SchedulingStrategy) *GameServerSetSpecApplyConfiguration {
	b.Scheduling = &value
	return b
}

// WithPriorities adds the given value to the Priorities field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Priorities field.
func (b *GameServerSetSpecApplyConfiguration) WithPriorities(values ...*PriorityApplyConfiguration) *GameServerSetSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithPriorities")
		}
		b.Priorities = append(b.Priorities, *values[i])
	}
	return b
}

// WithTemplate sets the Template field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Template field is set to the value of the last call.
func (b *GameServerSetSpecApplyConfiguration) WithTemplate(value *GameServerTemplateSpecApplyConfiguration) *GameServerSetSpecApplyConfiguration {
	b.Template = value
	return b
}
