// Copyright Contributors to Agones a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	agonesv1 "agones.dev/agones/pkg/apis/agones/v1"
	corev1 "k8s.io/api/core/v1"
)

// GameServerPortApplyConfiguration represents a declarative configuration of the GameServerPort type for use
// with apply.
//
// GameServerPort defines a set of Ports that
// are to be exposed via the GameServer
type GameServerPortApplyConfiguration struct {
	// Name is the descriptive name of the port
	Name *string `json:"name,omitempty"`
	// Range is the port range name from which to select a port when using a
	// 'Dynamic' or 'Passthrough' port policy.
	Range *string `json:"range,omitempty"`
	// PortPolicy defines the policy for how the HostPort is populated.
	// Dynamic port will allocate a HostPort within the selected MIN_PORT and MAX_PORT range passed to the controller
	// at installation time.
	// When `Static` portPolicy is specified, `HostPort` is required, to specify the port that game clients will
	// connect to
	// `Passthrough` dynamically sets the `containerPort` to the same value as the dynamically selected hostPort.
	// `None` portPolicy ignores `HostPort` and the `containerPort` (optional) is used to set the port on the GameServer instance.
	PortPolicy *agonesv1.PortPolicy `json:"portPolicy,omitempty"`
	// Container is the name of the container or sidecar container on which to open the port. Defaults to the game server container.
	Container *string `json:"container,omitempty"`
	// ContainerPort is the port that is being opened on the specified container's process
	ContainerPort *int32 `json:"containerPort,omitempty"`
	// HostPort the port exposed on the host for clients to connect to
	HostPort *int32 `json:"hostPort,omitempty"`
	// Protocol is the network protocol being used. Defaults to UDP. TCP and TCPUDP are other options.
	Protocol *corev1.Protocol `json:"protocol,omitempty"`
}

// GameServerPortApplyConfiguration constructs a declarative configuration of the GameServerPort type for use with
// apply.
func GameServerPort() *GameServerPortApplyConfiguration {
	return &GameServerPortApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *GameServerPortApplyConfiguration) WithName(value string) *GameServerPortApplyConfiguration {
	b.Name = &value
	return b
}

// WithRange sets the Range field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Range field is set to the value of the last call.
func (b *GameServerPortApplyConfiguration) WithRange(value string) *GameServerPortApplyConfiguration {
	b.Range = &value
	return b
}

// WithPortPolicy sets the PortPolicy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortPolicy field is set to the value of the last call.
func (b *GameServerPortApplyConfiguration) WithPortPolicy(value agonesv1.PortPolicy) *GameServerPortApplyConfiguration {
	b.PortPolicy = &value
	return b
}

// WithContainer sets the Container field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Container field is set to the value of the last call.
func (b *GameServerPortApplyConfiguration) WithContainer(value string) *GameServerPortApplyConfiguration {
	b.Container = &value
	return b
}

// WithContainerPort sets the ContainerPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ContainerPort field is set to the value of the last call.
func (b *GameServerPortApplyConfiguration) WithContainerPort(value int32) *GameServerPortApplyConfiguration {
	b.ContainerPort = &value
	return b
}

// WithHostPort sets the HostPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HostPort field is set to the value of the last call.
func (b *GameServerPortApplyConfiguration) WithHostPort(value int32) *GameServerPortApplyConfiguration {
	b.HostPort = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *GameServerPortApplyConfiguration) WithProtocol(value corev1.Protocol) *GameServerPortApplyConfiguration {
	b.Protocol = &value
	return b
}
