// Copyright Contributors to Agones a Series of LF Projects, LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// HealthApplyConfiguration represents a declarative configuration of the Health type for use
// with apply.
//
// Health configures health checking on the GameServer
type HealthApplyConfiguration struct {
	// Disabled is whether health checking is disabled or not
	Disabled *bool `json:"disabled,omitempty"`
	// PeriodSeconds is the number of seconds each health ping has to occur in
	PeriodSeconds *int32 `json:"periodSeconds,omitempty"`
	// FailureThreshold how many failures in a row constitutes unhealthy
	FailureThreshold *int32 `json:"failureThreshold,omitempty"`
	// InitialDelaySeconds initial delay before checking health
	InitialDelaySeconds *int32 `json:"initialDelaySeconds,omitempty"`
}

// HealthApplyConfiguration constructs a declarative configuration of the Health type for use with
// apply.
func Health() *HealthApplyConfiguration {
	return &HealthApplyConfiguration{}
}

// WithDisabled sets the Disabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Disabled field is set to the value of the last call.
func (b *HealthApplyConfiguration) WithDisabled(value bool) *HealthApplyConfiguration {
	b.Disabled = &value
	return b
}

// WithPeriodSeconds sets the PeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PeriodSeconds field is set to the value of the last call.
func (b *HealthApplyConfiguration) WithPeriodSeconds(value int32) *HealthApplyConfiguration {
	b.PeriodSeconds = &value
	return b
}

// WithFailureThreshold sets the FailureThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureThreshold field is set to the value of the last call.
func (b *HealthApplyConfiguration) WithFailureThreshold(value int32) *HealthApplyConfiguration {
	b.FailureThreshold = &value
	return b
}

// WithInitialDelaySeconds sets the InitialDelaySeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InitialDelaySeconds field is set to the value of the last call.
func (b *HealthApplyConfiguration) WithInitialDelaySeconds(value int32) *HealthApplyConfiguration {
	b.InitialDelaySeconds = &value
	return b
}
